In [2]:
import pandas as pd
import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
confirmed2 = pd.read_csv("us_confirmed_420.csv")
confirmed2

,UID,iso2,iso3,code3,FIPS,Admin2,Lat,Combined_Key,Date,Case,Long,Country/Region,Province/State
0,84001001,US,USA,840,1001.0,Autauga,32.539527,"Autauga, Alabama, US",4/20/20,28,-86.644082,US,Alabama
1,84001003,US,USA,840,1003.0,Baldwin,30.727750,"Baldwin, Alabama, US",4/20/20,117,-87.722071,US,Alabama
2,84001005,US,USA,840,1005.0,Barbour,31.868263,"Barbour, Alabama, US",4/20/20,22,-85.387129,US,Alabama
3,84001007,US,USA,840,1007.0,Bibb,32.996421,"Bibb, Alabama, US",4/20/20,32,-87.125115,US,Alabama
4,84001009,US,USA,840,1009.0,Blount,33.982109,"Blount, Alabama, US",4/20/20,22,-86.567906,US,Alabama
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3250,84070016,US,USA,840,NaN,Central Utah,39.372319,"Central Utah, Utah, US",4/20/20,17,-111.575868,US,Utah
3251,84070017,US,USA,840,NaN,Southeast Utah,38.996171,"Southeast Utah, Utah, US",4/20/20,7,-110.701396,US,Utah
3252,84070018,US,USA,840,NaN,Southwest Utah,37.854472,"Southwest Utah, Utah, US",4/20/20,70,-111.441876,US,Utah
3253,84070019,US,USA,840,NaN,TriCounty,40.124915,"TriCounty, Utah, US",4/20/20,10,-109.517442,US,Utah
3254,84070020,US,USA,840,NaN,Weber-Morgan,41.271160,"Weber-Morgan, Utah, US",4/20/20,124,-111.914512,US,Utah

In [64]:
confirmed_by_state = confirmed2.groupby("Province/State").sum()
confirmed_by_state2 = confirmed_by_state.drop("Diamond Princess")
confirmed_by_state2

,UID,code3,FIPS,Lat,Case,Long
Province/State,,,,,,
Alabama,5796241491,57960,241491.0,2203.246784,5079,-5809.578199
Alaska,2604232344,26040,232344.0,1747.579877,321,-4229.319334
Arizona,1428230216,14280,230216.0,505.138555,5068,-1671.948482
Arkansas,6468550635,64680,550635.0,2618.391704,1973,-6932.548370
California,5040521376,50400,521376.0,2194.949775,33686,-7002.258461
Colorado,5544685999,55440,685999.0,2491.870366,9730,-6751.119357
Connecticut,840242082,8400,242082.0,332.909441,19815,-581.254637
Delaware,420200029,4200,200029.0,117.327830,2745,-226.599712
District of Columbia,252181023,2520,181023.0,38.904178,2927,-77.016560
Florida,5796978574,57960,978574.0,1939.030577,27059,-5540.949842
Georgia,13526262703,135240,2262703.0,5216.556611,19407,-13288.811358
Hawaii,588245055,5880,245055.0,105.141415,584,-786.616182
Idaho,3864875968,38640,875968.0,1947.589655,1672,-5036.245496
Illinois,8737914438,87360,1914438.0,4064.049006,31513,-9096.189667
Indiana,7897834500,78960,1834500.0,3665.036491,11688,-7932.108297
Iowa,8486060839,84840,2060839.0,4160.961092,3159,-9253.086423
Kansas,8990281065,89880,2281065.0,4040.964784,2048,-10298.877911
Kentucky,10250704442,102480,2704442.0,4514.657262,3050,-10223.986874
Louisiana,5545582140,55440,1582140.0,1989.915353,24523,-5876.747946
Maine,1512538302,15120,538302.0,715.003014,875,-1112.380298
Maryland,2184747127,21840,747127.0,936.358097,13684,-1840.211223
Massachusetts,1428590248,14280,520246.0,630.994149,38077,-1071.277031
Michigan,7310474950,73080,2334941.0,3655.620467,32000,-7070.080729
Minnesota,7478526623,74760,2526623.0,3963.025129,2470,-8215.492913
Mississippi,7058472780,70560,2472780.0,2689.003578,4512,-7350.949516
Missouri,9915588598,99120,3518595.0,4460.984726,5890,-10729.940479
Montana,4873853196,48720,1853196.0,2630.582703,433,-6143.222113
Nebraska,7983061711,79800,3061711.0,3842.926930,1648,-9210.628137
Nevada,1596714838,15960,714838.0,667.351945,3830,-1998.587890
New Hampshire,1008500166,10080,500166.0,434.789729,1447,-715.776567
New Jersey,1932884509,19320,884509.0,846.015259,88722,-1567.071444
New Mexico,2941326065,29400,1326065.0,1140.128846,1971,-3494.274545
New York,5378405916,53760,2405916.0,2637.737383,253060,-4679.399365
North Carolina,8571880074,85680,3880074.0,3562.420971,6895,-7950.109874
North Dakota,4622186885,46200,2186885.0,2511.855857,627,-5313.217852
Ohio,7563609822,75600,3609822.0,3547.338944,12919,-7289.515905
Oklahoma,6639256009,66360,3256009.0,2733.647411,2680,-7488.357767
Oregon,3193647378,31920,1647378.0,1601.726424,1957,-4373.169106
Pennsylvania,5798988573,57960,2988573.0,2734.811250,33914,-5200.226295
Rhode Island,588390113,5880,390113.0,208.275711,5090,-357.320525
South Carolina,4034242206,40320,2242206.0,1562.043718,4446,-3725.236386
South Dakota,5715210577,57120,3210577.0,2921.997865,1685,-6554.501988
Tennessee,8152644119,81480,4644119.0,3409.084710,7238,-8180.328684
Texas,21516426612,215040,12426612.0,8041.803434,19751,-25057.879425
Utah,3110012044,31080,1591939.0,1388.550986,3213,-3904.519943
Vermont,1344870296,13440,870296.0,618.232941,816,-1017.581330
Virginia,11346988213,113400,6988213.0,4996.297993,8990,-10442.323661
Washington,3446238627,34440,2238627.0,1842.117670,12114,-4708.049596
West Virginia,4791143133,47880,3143133.0,2134.783954,902,-4433.959998
Wisconsin,6220135229,62160,4135229.0,3196.450332,4499,-6465.454559
Wyoming,2101458641,21000,1458641.0,990.998367,317,-2464.524571

In [66]:
confirmed_by_state2['state'] = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']

In [68]:
states = confirmed_by_state2.set_index("state")

In [70]:
states2 = states.drop(labels=["UID", "code3", "FIPS", "Lat", "Long"], axis=1)

In [73]:
states2

         Case
state
AL       5079
AK        321
AZ       5068
AR       1973
CA      33686
CO       9730
CT      19815
DE       2745
DC       2927
FL      27059
GA      19407
HI        584
ID       1672
IL      31513
IN      11688
IA       3159
KS       2048
KY       3050
LA      24523
ME        875
MD      13684
MA      38077
MI      32000
MN       2470
MS       4512
MO       5890
MT        433
NE       1648
NV       3830
NH       1447
NJ      88722
NM       1971
NY     253060
NC       6895
ND        627
OH      12919
OK       2680
OR       1957
PA      33914
RI       5090
SC       4446
SD       1685
TN       7238
TX      19751
UT       3213
VT        816
VA       8990
WA      12114
WV        902
WI       4499
WY        317

In [72]:
states2.to_csv("cases_by_state.csv")

In [48]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'}

In [42]:
as_list = confirmed_by_state.index.tolist()
for state in as_list:
    if state in us_state_abbrev.keys():
        state = us_state_abbrev.get(state)